[vale_vitoria]
plc_esteira_01 ansible_host=10.50.1.10
plc_britador_02 ansible_host=10.50.1.11

[vale_itabira]
sensor_pressao_05 ansible_host=10.60.4.55

[ot_devices:children]
vale_vitoria
vale_itabira