name: Code Quality
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Flake8
        # Aqui forçamos as regras direto no comando para não depender do setup.cfg
        run: flake8 library/ scripts/ tests/ --max-line-length=160 --ignore=E402,W503,F401
